from django.urls import path, re_path
from django.conf import settings
from django.conf.urls.static import static
from . import views
from django.views.static import serve 

urlpatterns = [ 
    path('', views.home_view, name='home'),
    path('auth_register/', views.register_view, name='auth_register'),
    path('auth_login/', views.login_view, name='auth_login'),
    path('logout/', views.LogoutView, name='logout'),
    path('super/', views.stake_register_view, name='super'),
    path('login_view/', views.login_view, name='login_view'),
    path('user_registration/', views.user_registration, name='user_registration'),
    path('Registeration/', views.Registeration, name='Registeration'),
    path('ministry/<str:category>/', views.ministry_view, name='ministry'),
    path('membership/<str:category>/', views.membership_view, name='membership'),
    path('junior-church/<str:category>/', views.junior_church_view, name='junior_church'),
    path('church/hill/', views.hill, name='hill_church'),
    path('church/sakponba/', views.sakponba_view, name='sakponba_church'),
    path('church/uselu/', views.uselu_view, name='uselu_church'),
    path('birthday_adverts/<str:category>/', views.birthday_adverts_view, name='birthday_adverts'),
    path('social-media/<str:category>/', views.social_media_report, name='social-media'),
    path('missions/summary/', views.missions_summary, name='missions_summary'),
    path('profile/', views.profile_views, name='profile'),
    path('update-profile-picture/', views.update_profile_picture, name='update_profile_picture'),
    path('update-profile/', views.update_profile, name='update_profile'),
    path('no_permission/', views.no_permission, name='no_permission'),
    path('locked_until_thursday/', views.locked_until_thursday, name='locked_until_thursday'),
    path('locked_need_to_pay_fine/', views.locked_need_to_pay_fine, name='locked_need_to_pay_fine'),
    path('locked/', views.locked, name='locked'),
    path('admin/update-can-submit-permissions/', views.update_can_submit_permissions, name='update_can_submit_permissions'),
    path('update_ministry_records/<str:category>/update/', views.update_ministry_records, name='update_ministry_records'),
    path('update_membership_records/<str:category>/', views.update_membership_records, name='update_membership_records'),
    path('update_junior_records/<str:category>/', views.update_Junior_records, name='update_junior_records'),
    path('update_multimedia_records/<str:category>/', views.update_multimedia_records, name='update_multimedia_records'),
    path('update_social_media_Report/<str:category>/', views.update_social_media_Report, name='update_social_media_Report'),
    path('Sakponba_update/<str:category>/',views.Sakponba_update_view,name='Sakponba_update'),
    path('Uselu_update/<str:category>/',views.Uselu_update_view,name='Uselu_update'),
    path('Hill_update/<str:category>/',views.Hill_update_view,name='Hill_update'),
    path('missions/<int:pk>/edit-inline/', views.mission_edit_inline, name='mission-edit-inline'),
    path('verication/',views.verication_views,name='verication'),
    path('verify_registration/', views.verify_registration, name='verify_registration'),
    path('resend_verification/', views.resend_verification_code, name='resend_verification'),
    path('send_reset_code/',views.send_reset_code_view, name='send_reset_code'),
    path('reset_password/', views.reset_password_view, name='reset_password'),
    path('send-verification-code/', views.send_verification_code, name='send_verification_code'),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
