# Generated by Django 5.2.1 on 2025-05-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirthdayAdvert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('churches', models.CharField(choices=[('1', 'Church 1'), ('2', 'Church 2')], max_length=1, verbose_name='Church')),
                ('total', models.PositiveIntegerField(default=0, help_text='Total number of birthday adverts')),
                ('date', models.DateField(auto_now_add=True, help_text='Date this record was created')),
            ],
            options={
                'verbose_name': 'Birthday Advert',
                'verbose_name_plural': 'Birthday Adverts',
            },
        ),
        migrations.CreateModel(
            name='HillChurch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_day', models.CharField(choices=[('sunday', 'Sunday'), ('wednesday', 'Wednesday')], max_length=9, verbose_name='Service Day')),
                ('service_no', models.CharField(choices=[('1', '1st Service'), ('2', '2nd Service')], max_length=1, verbose_name='Service Number')),
                ('male', models.PositiveIntegerField(default=0)),
                ('female', models.PositiveIntegerField(default=0)),
                ('children', models.PositiveIntegerField(default=0)),
                ('attendance_total', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('number_of_cars', models.PositiveIntegerField(default=0)),
                ('offering', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tithe', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('transfer', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('financial_total', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=14, null=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hill Church Service',
                'verbose_name_plural': 'Hill Church Services',
            },
        ),
        migrations.CreateModel(
            name='JuniorChurch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('churches', models.CharField(choices=[('1', 'Church 1'), ('2', 'Church 2')], max_length=1)),
                ('service', models.CharField(choices=[('1', 'Service 1'), ('2', 'Service 2')], max_length=1)),
                ('church_type', models.CharField(choices=[('children', 'Children Church'), ('teens', 'Teens Church')], max_length=10)),
                ('creche', models.PositiveIntegerField(default=0)),
                ('adorable', models.PositiveIntegerField(default=0)),
                ('angels', models.PositiveIntegerField(default=0)),
                ('shining_stars', models.PositiveIntegerField(default=0)),
                ('great_minds', models.PositiveIntegerField(default=0)),
                ('sparkles', models.PositiveIntegerField(default=0)),
                ('total_children', models.PositiveIntegerField(blank=True, null=True)),
                ('children_offering', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('children_tithe', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('children_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_teens', models.PositiveIntegerField(default=0)),
                ('teens_offering', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('teens_tithe', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('teens_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('churches', models.CharField(choices=[('1', 'Church 1'), ('2', 'Church 2')], max_length=1)),
                ('service', models.CharField(choices=[('1', 'Service 1'), ('2', 'Service 2'), ('3', 'Service 3')], max_length=1)),
                ('first_time_guests', models.PositiveIntegerField(default=0)),
                ('second_time_guests', models.PositiveIntegerField(default=0)),
                ('number_called', models.PositiveIntegerField(default=0)),
                ('number_of_sms', models.PositiveIntegerField(default=0)),
                ('membership_interest', models.PositiveIntegerField(default=0)),
                ('number_of_converts', models.PositiveIntegerField(default=0)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Ministry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('churches', models.CharField(choices=[('1', 'Church 1'), ('2', 'Church 2')], max_length=1)),
                ('sunday_wednesday', models.CharField(choices=[('sunday_wednesday', 'Sunday & Wednesday'), ('sunday', 'Sunday'), ('wednesday', 'Wednesday')], max_length=20)),
                ('service', models.CharField(choices=[('1', 'Service 1'), ('2', 'Service 2'), ('3', 'Service 3')], max_length=1)),
                ('male', models.PositiveIntegerField(default=0)),
                ('female', models.PositiveIntegerField(default=0)),
                ('children', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(blank=True, null=True)),
                ('number_of_cars', models.PositiveIntegerField(default=0)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='MissionTeamSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('evbuotubu', models.PositiveIntegerField(default=0, help_text='Count at Evbuotubu')),
                ('gra', models.PositiveIntegerField(default=0, help_text='Count at GRA')),
                ('total_first_time_guests', models.PositiveIntegerField(default=0)),
                ('reached_first_time_guests', models.PositiveIntegerField(default=0)),
                ('not_reachable_first_time_guests', models.PositiveIntegerField(default=0)),
                ('visitors_and_outsiders', models.PositiveIntegerField(default=0)),
                ('committed_to_second_visit', models.PositiveIntegerField(default=0)),
                ('committed_to_believers_academy', models.PositiveIntegerField(default=0)),
                ('attended_cell_meeting_same_day', models.PositiveIntegerField(default=0)),
                ('committed_to_cell_meeting_next_week', models.PositiveIntegerField(default=0)),
                ('second_time_visitors_previous_week', models.PositiveIntegerField(default=0)),
                ('grand_total', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SakponbaChurch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_day', models.CharField(choices=[('sunday', 'Sunday'), ('wednesday', 'Wednesday')], max_length=9, verbose_name='Service Day')),
                ('service_no', models.CharField(choices=[('1', '1st Service'), ('2', '2nd Service')], max_length=1, verbose_name='Service Number')),
                ('male', models.PositiveIntegerField(default=0)),
                ('female', models.PositiveIntegerField(default=0)),
                ('children', models.PositiveIntegerField(default=0)),
                ('attendance_total', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('number_of_cars', models.PositiveIntegerField(default=0)),
                ('offering', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tithe', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('transfer', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('financial_total', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=14, null=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sakponba Church Service',
                'verbose_name_plural': 'Sakponba Church Services',
            },
        ),
        migrations.CreateModel(
            name='SocialMediaReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('churches', models.CharField(choices=[('1', 'Church 1'), ('2', 'Church 2')], max_length=100, verbose_name='Church')),
                ('sotw', models.CharField(choices=[('facebook', 'Facebook'), ('youtube', 'YouTube')], max_length=100, verbose_name='Platform')),
                ('service', models.CharField(choices=[('1', 'Service 1'), ('2', 'Service 2'), ('3', 'Service 3')], max_length=100, verbose_name='Service')),
                ('facebook_count', models.PositiveIntegerField(default=0, help_text='Metric (e.g. likes/views) on Facebook')),
                ('youtube_count', models.PositiveIntegerField(default=0, help_text='Metric (e.g. likes/views) on YouTube')),
                ('date', models.DateField(auto_now_add=True, help_text='Date this report was created')),
            ],
            options={
                'verbose_name': 'Social Media Report',
                'verbose_name_plural': 'Social Media Reports',
            },
        ),
        migrations.CreateModel(
            name='UseluChurch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_day', models.CharField(choices=[('sunday', 'Sunday'), ('wednesday', 'Wednesday')], max_length=9, verbose_name='Service Day')),
                ('service_no', models.CharField(choices=[('1', '1st Service'), ('2', '2nd Service')], max_length=1, verbose_name='Service Number')),
                ('male', models.PositiveIntegerField(default=0)),
                ('female', models.PositiveIntegerField(default=0)),
                ('children', models.PositiveIntegerField(default=0)),
                ('attendance_total', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('number_of_cars', models.PositiveIntegerField(default=0)),
                ('offering', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tithe', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('transfer', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('financial_total', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=14, null=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Uselu Church Service',
                'verbose_name_plural': 'Uselu Church Services',
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=100)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
