# Generated by Django 5.2.1 on 2025-05-20 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_delete_hillchurch_delete_sakponbachurch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HillChurch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_day', models.CharField(choices=[('sunday', 'Sunday'), ('wednesday', 'Wednesday')], max_length=9, verbose_name='Service Day')),
                ('service_no', models.CharField(choices=[('1', '1st Service'), ('2', '2nd Service')], max_length=1, verbose_name='Service Number')),
                ('male', models.PositiveIntegerField(default=0)),
                ('female', models.PositiveIntegerField(default=0)),
                ('children', models.PositiveIntegerField(default=0)),
                ('attendance_total', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('number_of_cars', models.PositiveIntegerField(default=0)),
                ('offering', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tithe', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('transfer', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('financial_total', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=14, null=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hill Church Service',
                'verbose_name_plural': 'Hill Church Services',
            },
        ),
        migrations.CreateModel(
            name='SakponbaChurch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_day', models.CharField(choices=[('sunday', 'Sunday'), ('wednesday', 'Wednesday')], max_length=9, verbose_name='Service Day')),
                ('service_no', models.CharField(choices=[('1', '1st Service'), ('2', '2nd Service')], max_length=1, verbose_name='Service Number')),
                ('male', models.PositiveIntegerField(default=0)),
                ('female', models.PositiveIntegerField(default=0)),
                ('children', models.PositiveIntegerField(default=0)),
                ('attendance_total', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('number_of_cars', models.PositiveIntegerField(default=0)),
                ('offering', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tithe', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('transfer', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('financial_total', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=14, null=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sakponba Church Service',
                'verbose_name_plural': 'Sakponba Church Services',
            },
        ),
        migrations.CreateModel(
            name='UseluChurch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_day', models.CharField(choices=[('sunday', 'Sunday'), ('wednesday', 'Wednesday')], max_length=9, verbose_name='Service Day')),
                ('service_no', models.CharField(choices=[('1', '1st Service'), ('2', '2nd Service')], max_length=1, verbose_name='Service Number')),
                ('male', models.PositiveIntegerField(default=0)),
                ('female', models.PositiveIntegerField(default=0)),
                ('children', models.PositiveIntegerField(default=0)),
                ('attendance_total', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('number_of_cars', models.PositiveIntegerField(default=0)),
                ('offering', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tithe', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('transfer', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('financial_total', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=14, null=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Uselu Church Service',
                'verbose_name_plural': 'Uselu Church Services',
            },
        ),
    ]
