# Generated by Django 5.2.1 on 2025-05-20 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_hillchurch_sakponbachurch_useluchurch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missionteamsummary',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
