# Generated by Django 5.2.1 on 2025-05-20 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_missionteamsummary_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='missionteamsummary',
            old_name='attended_cell_meeting_same_day',
            new_name='attended_cell_meeting_same_day_evbuotubu',
        ),
        migrations.RenameField(
            model_name='missionteamsummary',
            old_name='committed_to_believers_academy',
            new_name='attended_cell_meeting_same_day_gra',
        ),
        migrations.RenameField(
            model_name='missionteamsummary',
            old_name='committed_to_cell_meeting_next_week',
            new_name='committed_to_believers_academy_evbuotubu',
        ),
        migrations.RenameField(
            model_name='missionteamsummary',
            old_name='committed_to_second_visit',
            new_name='committed_to_believers_academy_gra',
        ),
        migrations.RenameField(
            model_name='missionteamsummary',
            old_name='not_reachable_first_time_guests',
            new_name='committed_to_cell_meeting_next_week_evbuotubu',
        ),
        migrations.RenameField(
            model_name='missionteamsummary',
            old_name='reached_first_time_guests',
            new_name='committed_to_cell_meeting_next_week_gra',
        ),
        migrations.RenameField(
            model_name='missionteamsummary',
            old_name='second_time_visitors_previous_week',
            new_name='committed_to_second_visit_evbuotubu',
        ),
        migrations.RenameField(
            model_name='missionteamsummary',
            old_name='total_first_time_guests',
            new_name='committed_to_second_visit_gra',
        ),
        migrations.RenameField(
            model_name='missionteamsummary',
            old_name='visitors_and_outsiders',
            new_name='not_reachable_first_time_guests_evbuotubu',
        ),
        migrations.AddField(
            model_name='missionteamsummary',
            name='not_reachable_first_time_guests_gra',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='missionteamsummary',
            name='reached_first_time_guests_evbuotubu',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='missionteamsummary',
            name='reached_first_time_guests_gra',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='missionteamsummary',
            name='second_time_visitors_previous_week_evbuotubu',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='missionteamsummary',
            name='second_time_visitors_previous_week_gra',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='missionteamsummary',
            name='total_first_time_guests_evbuotubu',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='missionteamsummary',
            name='total_first_time_guests_gra',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='missionteamsummary',
            name='visitors_and_outsiders_evbuotubu',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='missionteamsummary',
            name='visitors_and_outsiders_gra',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
