# Generated by Django 5.2.1 on 2025-05-24 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_account_phone_number_account_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirthdayAdvertChurch1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.PositiveIntegerField(default=0, help_text='Total number of birthday adverts')),
                ('date', models.DateField(auto_now_add=True, help_text='Date this record was created')),
            ],
            options={
                'verbose_name': 'Birthday Advert Church 1',
                'verbose_name_plural': 'Birthday Adverts Church 1',
            },
        ),
        migrations.CreateModel(
            name='BirthdayAdvertChurch2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.PositiveIntegerField(default=0, help_text='Total number of birthday adverts')),
                ('date', models.DateField(auto_now_add=True, help_text='Date this record was created')),
            ],
            options={
                'verbose_name': 'Birthday Advert Church 2',
                'verbose_name_plural': 'Birthday Adverts Church 2',
            },
        ),
        migrations.CreateModel(
            name='JuniorChurchChurch1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('1', 'Service 1'), ('2', 'Service 2')], max_length=1)),
                ('church_type', models.CharField(choices=[('children', 'Children Church'), ('teens', 'Teens Church')], max_length=10)),
                ('creche', models.PositiveIntegerField(default=0)),
                ('adorable', models.PositiveIntegerField(default=0)),
                ('angels', models.PositiveIntegerField(default=0)),
                ('shining_stars', models.PositiveIntegerField(default=0)),
                ('great_minds', models.PositiveIntegerField(default=0)),
                ('sparkles', models.PositiveIntegerField(default=0)),
                ('total_children', models.PositiveIntegerField(blank=True, null=True)),
                ('children_offering', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('children_tithe', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('children_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_teens', models.PositiveIntegerField(default=0)),
                ('teens_offering', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('teens_tithe', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('teens_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='JuniorChurchChurch2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('1', 'Service 1'), ('2', 'Service 2')], max_length=1)),
                ('church_type', models.CharField(choices=[('children', 'Children Church'), ('teens', 'Teens Church')], max_length=10)),
                ('creche', models.PositiveIntegerField(default=0)),
                ('adorable', models.PositiveIntegerField(default=0)),
                ('angels', models.PositiveIntegerField(default=0)),
                ('shining_stars', models.PositiveIntegerField(default=0)),
                ('great_minds', models.PositiveIntegerField(default=0)),
                ('sparkles', models.PositiveIntegerField(default=0)),
                ('total_children', models.PositiveIntegerField(blank=True, null=True)),
                ('children_offering', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('children_tithe', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('children_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_teens', models.PositiveIntegerField(default=0)),
                ('teens_offering', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('teens_tithe', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('teens_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MembershipChurch1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('1', 'Service 1'), ('2', 'Service 2'), ('3', 'Service 3')], max_length=1)),
                ('first_time_guests', models.PositiveIntegerField(default=0)),
                ('second_time_guests', models.PositiveIntegerField(default=0)),
                ('number_called', models.PositiveIntegerField(default=0)),
                ('number_of_sms', models.PositiveIntegerField(default=0)),
                ('membership_interest', models.PositiveIntegerField(default=0)),
                ('number_of_converts', models.PositiveIntegerField(default=0)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MembershipChurch2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('1', 'Service 1'), ('2', 'Service 2'), ('3', 'Service 3')], max_length=1)),
                ('first_time_guests', models.PositiveIntegerField(default=0)),
                ('second_time_guests', models.PositiveIntegerField(default=0)),
                ('number_called', models.PositiveIntegerField(default=0)),
                ('number_of_sms', models.PositiveIntegerField(default=0)),
                ('membership_interest', models.PositiveIntegerField(default=0)),
                ('number_of_converts', models.PositiveIntegerField(default=0)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MinistryChurch1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sunday_wednesday', models.CharField(choices=[('sunday_wednesday', 'Sunday & Wednesday'), ('sunday', 'Sunday'), ('wednesday', 'Wednesday')], max_length=20)),
                ('service', models.CharField(choices=[('1', 'Service 1'), ('2', 'Service 2'), ('3', 'Service 3')], max_length=1)),
                ('male', models.PositiveIntegerField(default=0)),
                ('female', models.PositiveIntegerField(default=0)),
                ('children', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(blank=True, null=True)),
                ('number_of_cars', models.PositiveIntegerField(default=0)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MinistryChurch2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sunday_wednesday', models.CharField(choices=[('sunday_wednesday', 'Sunday & Wednesday'), ('sunday', 'Sunday'), ('wednesday', 'Wednesday')], max_length=20)),
                ('service', models.CharField(choices=[('1', 'Service 1'), ('2', 'Service 2'), ('3', 'Service 3')], max_length=1)),
                ('male', models.PositiveIntegerField(default=0)),
                ('female', models.PositiveIntegerField(default=0)),
                ('children', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(blank=True, null=True)),
                ('number_of_cars', models.PositiveIntegerField(default=0)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialMediaReportChurch1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sotw', models.CharField(choices=[('facebook', 'Facebook'), ('youtube', 'YouTube')], max_length=100, verbose_name='Platform')),
                ('service', models.CharField(choices=[('1', 'Service 1'), ('2', 'Service 2'), ('3', 'Service 3')], max_length=100, verbose_name='Service')),
                ('facebook_count', models.PositiveIntegerField(default=0, help_text='Metric (e.g. likes/views) on Facebook')),
                ('youtube_count', models.PositiveIntegerField(default=0, help_text='Metric (e.g. likes/views) on YouTube')),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialMediaReportChurch2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sotw', models.CharField(choices=[('facebook', 'Facebook'), ('youtube', 'YouTube')], max_length=100, verbose_name='Platform')),
                ('service', models.CharField(choices=[('1', 'Service 1'), ('2', 'Service 2'), ('3', 'Service 3')], max_length=100, verbose_name='Service')),
                ('facebook_count', models.PositiveIntegerField(default=0, help_text='Metric (e.g. likes/views) on Facebook')),
                ('youtube_count', models.PositiveIntegerField(default=0, help_text='Metric (e.g. likes/views) on YouTube')),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='BirthdayAdvert',
        ),
        migrations.DeleteModel(
            name='JuniorChurch',
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
        migrations.DeleteModel(
            name='Ministry',
        ),
        migrations.DeleteModel(
            name='SocialMediaReport',
        ),
    ]
