# Generated by Django 5.2.1 on 2025-05-24 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_birthdayadvertchurch1_birthdayadvertchurch2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipchurch1',
            name='service',
            field=models.CharField(choices=[('1', '1st Service'), ('2', '2nd Service'), ('3', '3rd Service')], max_length=1),
        ),
        migrations.AlterField(
            model_name='membershipchurch2',
            name='service',
            field=models.CharField(choices=[('1', '1st Service'), ('2', '2nd Service'), ('3', '3rd Service')], max_length=1),
        ),
        migrations.AlterField(
            model_name='ministrychurch1',
            name='service',
            field=models.CharField(choices=[('1', '1st Service'), ('2', '2nd Service'), ('3', '3rd Service')], max_length=1),
        ),
        migrations.AlterField(
            model_name='ministrychurch2',
            name='service',
            field=models.CharField(choices=[('1', '1st Service'), ('2', '2nd Service'), ('3', '3rd Service')], max_length=1),
        ),
    ]
