# Generated by Django 5.2.1 on 2025-05-26 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_account_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('ministry_church_1', 'Ministry Church 1'), ('ministry_church_2', 'Ministry Church 2'), ('membership_church_1', 'Membership Church 1'), ('membership_church_2', 'Membership Church 2'), ('junior_church_1', 'Junior Church 1'), ('junior_church_2', 'Junior Church 2'), ('multimedia_church_1', 'Multimedia Church 1'), ('multimedia_church_2', 'Multimedia Church 2'), ('social_media_report', 'Social Media Report'), ('missions_team_summary', 'Missions Team Summary'), ('sakponba_church', 'Sakponba Church'), ('uselu_church', 'Uselu Church'), ('hill_church', 'Hill Church')], default='user', max_length=500),
        ),
    ]
