# Generated by Django 5.2.1 on 2025-05-27 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_birthdayadvertchurch1_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='can_submit_despite_missing_last_week',
            field=models.BooleanField(default=False),
        ),
    ]
