# Generated by Django 5.2.1 on 2025-06-02 10:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_userverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='missionteamsummary',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
